### ISSUE TITLE
Page Template: Content (Internal) Page

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-sandbox#38]
Page Template: Content (Internal) Page
https://drive.google.com/file/d/11jPYIe2KdNaJgouVM3BOGaeXrQkn2Rc7/view

**Tasks to complete**
- [x] add basic page components
- [x] add colors to theme
- [x] create template page
- [x] visual QA by Allie
- [x] review by Dan / Ammie
- [x] Chaz to review PRs
- [x] review and knowledge share: email team with PR, option to talk more at team meetings
- [x]  deliver for feedback

**DOD**
- [x] template pages are html w CSS and Java Script with custom style applied 
- [x] ability share out to various teams to apply apply text, image, and custom changes
- [x] ability to use with Drupal implementation
- [x] guidance and recommendations incorporated into build as needed
